// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-XETmm8_0SrTCkj3SwpzpJfenyjDDsZM',
    appId: '1:997710099034:web:25577a06735c84744a9e63',
    messagingSenderId: '997710099034',
    projectId: 'todoappfire-64841',
    authDomain: 'todoappfire-64841.firebaseapp.com',
    storageBucket: 'todoappfire-64841.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDndao4ZPTaMuC3rU7-7ZiqxWAiYPsgON4',
    appId: '1:997710099034:android:6f8e10406c77f5174a9e63',
    messagingSenderId: '997710099034',
    projectId: 'todoappfire-64841',
    storageBucket: 'todoappfire-64841.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlOH31DuQZU5d5D8_CqQIHDEjojChjoZ0',
    appId: '1:997710099034:ios:42d08a6b5c8cc1f44a9e63',
    messagingSenderId: '997710099034',
    projectId: 'todoappfire-64841',
    storageBucket: 'todoappfire-64841.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlOH31DuQZU5d5D8_CqQIHDEjojChjoZ0',
    appId: '1:997710099034:ios:42d08a6b5c8cc1f44a9e63',
    messagingSenderId: '997710099034',
    projectId: 'todoappfire-64841',
    storageBucket: 'todoappfire-64841.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-XETmm8_0SrTCkj3SwpzpJfenyjDDsZM',
    appId: '1:997710099034:web:a20ffd85aed6aaf44a9e63',
    messagingSenderId: '997710099034',
    projectId: 'todoappfire-64841',
    authDomain: 'todoappfire-64841.firebaseapp.com',
    storageBucket: 'todoappfire-64841.firebasestorage.app',
  );
}
